ENV_OPEN_ID = 'OPEN_ID'
ENV_HOST = 'HOST'
ENV_PORT = 'PORT'
ENV_PREFIX = 'PREFIX'
ENV_USERNAME = 'USERNAME'
ENV_TOKEN = 'TOKEN'
ENV_IMSDK_NAME = 'IMSDK_NAME'

CONFIG_SEND_METHOD = 'fn_send_request'
CONFIG_URL = 'url'
CONFIG_LOG_URL = 'log_url'
CONFIG_TOKEN = 'token'
CONFIG_IMSDK_NAME = 'imsdk_name'
CONFIG_USERNAME = 'username'
CONFIG_HOST = 'host'
CONFIG_PORT = 'port'

ERROR_CMD_FORMAT = '命令格式错误。'

TEMPLATE_URL = 'http://%s:%s%s/imsdk'
TEMPLATE_LOG_URL = 'http://%s:%s%s/imsdk/log'

FLASK_APP_NAME = 'anywhere_door_imsdk_larkbot'
FLASK_STATIC_FOLDER = './'
FLASK_URL_IMSDK = '/imsdk'
FLASK_HOST = '0.0.0.0'
FLASK_PORT = 80

PARAMS_TOKEN = 'token'
PARAMS_NAME = 'name'
PARAMS_TARGET = 'target'
PARAMS_DATA = 'data'
PARAMS_CODE = 'code'
PARAMS_MESSAGE = 'message'
PARAMS_USERNAME = 'username'
PARAMS_TIMESTAMP = 'timestamp'
PARAMS_LEVEL = 'level'
PARAMS_TAG = 'tag'
PARAMS_LOG = 'log'

ERROR_CODE_SUCCESS = 0
ERROR_CODE_INVALID_TOKEN = -1
ERROR_CODE_INVALID_TARGET = -2

ERROR_MESSAGE_SUCCESS = 'success'
ERROR_MESSAGE_INVALID_TOKEN = 'token is invalid'
ERROR_MESSAGE_INVALID_TARGET = 'target is not this'

TEXT = 'text'
OPEN_ID = 'open_id'
EMPTY_STR = ''

FROM = 'from'
WHITE_SPACE = ' '
NEWLINE = '\n'
COLON = ':'

LOG_LEVEL_DEBUG = 1
LOG_LEVEL_INFO = 2
LOG_LEVEL_WARN = 3
LOG_LEVEL_ERROR = 4
